### ISSUE TITLE
Generating edge maps not working

### ISSUE THREAD

**Issue by Derdiry** [hellozhuo/pidinet#58]
python main.py --model pidinet --config carv4 --sa --dil --resume --iter-size 24 -j 4 --gpu 0 --epochs 20 --lr 0.005 --lr-type multistep --lr-steps 10-16 --wd 1e-4 --savedir output --datadir input --dataset BSDS
 resulting : 
initialization done
conv weights: lr 0.005000, wd 0.000100	bn weights: lr 0.005000, wd 0.000010	relu weights: lr 0.005000, wd 0.000000
cuda is not used, the running might be slow
Threshold for ground truth: 76.800000 on BSDS_VOC
Threshold for ground truth: 76.800000 on BSDS_VOC
Traceback (most recent call last):
  File "C:\Users\Al Gadi\Downloads\pidinet-master\pidinet-master\main.py", line 418, in <module>
    main(f)
  File "C:\Users\Al Gadi\Downloads\pidinet-master\pidinet-master\main.py", line 228, in main
    tr_avg_loss = train(
  File "C:\Users\Al Gadi\Downloads\pidinet-master\pidinet-master\main.py", line 280, in train
    loss += cross_entropy_loss_RCF(o, label, args.lmbda)
  File "C:\Users\Al Gadi\Downloads\pidinet-master\pidinet-master\utils.py", line 150, in cross_entropy_loss_RCF
    cost = F.binary_cross_entropy(
  File "C:\Users\Al Gadi\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\functional.py", line 3122, in binary_cross_entropy
    return torch._C._nn.binary_cross_entropy(input, target, weight, reduction_enum)
RuntimeError: all elements of target should be between 0 and 1
![Screenshot 2024-06-13 160351](https://github.com/hellozhuo/pidinet/assets/61592363/166c21a0-83a4-42c6-999c-f5b4cc6edd09)

**Comment by LeiXuAI** [comment]
if you degrade your pytorch to version 1.XX, it will work.
